version: '3'
services:
  hyuabot-postgresql:
      image: postgres:latest
      restart: always
      expose:
        - 5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - ./data/:/var/lib/postgresql/data/
  hyuabot-api:
      build: ./api
      environment:
        - POSTGRES_HOST=hyuabot-postgresql
        - BUS_API_KEY=${BUS_API_KEY}
        - METRO_API_KEY=${METRO_API_KEY}
        - TZ=Asia/Seoul
      ports:
        - 38080:8080
      depends_on:
        - hyuabot-postgresql
      volumes:
        - /etc/localtime:/etc/localtime:ro
  hyuabot-kakao:
      build: ./kakao
      environment:
        - API_HOST=hyuabot-api
        - TZ=Asia/Seoul
      ports:
        - 38081:8081
      depends_on:
        - hyuabot-postgresql
        - hyuabot-api
      volumes:
        - /etc/localtime:/etc/localtime:ro